### ISSUE TITLE
USB-Support (Question)

### ISSUE THREAD

**Issue by mbutz** [szymonkaliski/diy-monome#2]
Hi,

just a question: I have an Adafruit Unztrument (Trellis based) running with an Arduino Leonardo which supports an USB connection. Do you have any plans to adapt your solution to support USB?

Martin

**Comment by szymonkaliski** [comment]
Hey Martin, what do you mean by "usb support"? I'm plugging diy monome with usb cable :)

**Comment by mbutz** [comment]
Hi Szymon,

thanks for the feedback and sorry for my ignorance. I am very new to the Arduino platform. I will try how far I get with your library and also use my USB cable ;)

Your solution is the only one I could find on Gitub. The Arduinome project seems to be not supported anymore.

Thanks again
Martin
