### ISSUE TITLE
Error: call of overloaded 'write(int)' is ambiguous

### ISSUE THREAD

**Issue by mbutz** [szymonkaliski/diy-monome#3]
Hi Szymon,

tried to compile and upload the trellis-monome library to my Adafruit Unztrument and got the following error(s). Can you help?

```
/home/marty/projects/sonicpi/arduino/code/trellis-monome/trellis-monome/trellis-monome-0.5.1/trellis-monome-0.5.1.ino: In function 'void checkButtons()':
trellis-monome-0.5.1:217: error: call of overloaded 'write(int)' is ambiguous
                Serial.write((0 << 4) | (0 & 15)); 
                                                ^
/home/marty/projects/sonicpi/arduino/code/trellis-monome/trellis-monome/trellis-monome-0.5.1/trellis-monome-0.5.1.ino:217:48: note: candidates are:
In file included from /home/marty/bin/arduino-1.8.5/hardware/arduino/avr/cores/arduino/Arduino.h:233:0,
                 from sketch/trellis-monome-0.5.1.ino.cpp:1:
/home/marty/bin/arduino-1.8.5/hardware/arduino/avr/cores/arduino/USBAPI.h:103:17: note: virtual size_t Serial_::write(uint8_t)
  virtual size_t write(uint8_t);
                 ^
In file included from /home/marty/bin/arduino-1.8.5/hardware/arduino/avr/cores/arduino/Stream.h:26:0,
                 from /home/marty/bin/arduino-1.8.5/hardware/arduino/avr/cores/arduino/HardwareSerial.h:29,
                 from /home/marty/bin/arduino-1.8.5/hardware/arduino/avr/cores/arduino/Arduino.h:232,
                 from sketch/trellis-monome-0.5.1.ino.cpp:1:
/home/marty/bin/arduino-1.8.5/hardware/arduino/avr/cores/arduino/Print.h:52:12: note: size_t Print::write(const char*)
     size_t write(const char *str) {
            ^
exit status 1
call of overloaded 'write(int)' is ambiguous
```

**Comment by szymonkaliski** [comment]
Hm, that's strange, it seems to point to error on line 217 with `Serial.write((0 << 4) | (0 & 15));` but we don't have that line in the code:

- here's line 217: https://github.com/szymonkaliski/diy-monome/blob/master/Trellinome/Trellinome.ino#L217
- it also points to `void checkButtons()` function that again, is nowhere in this code

I just opened https://github.com/szymonkaliski/diy-monome/blob/master/Trellinome/Trellinome.ino in Arduino 1.8.7 and hit "compile" and I'm getting no errors. Keep in mind that you need the Trellis library from Adafruit.

Can you let me know bit more of what you're trying to do? Are you modyfying anything? The only thing that you should probably change is this: https://github.com/szymonkaliski/diy-monome/blob/master/Trellinome/Trellinome.ino#L93-L94

**Comment by mbutz** [comment]
Hi Szymon,

well, it is not that often that I am outing myself as stupid twice in a row ;) But this time I did. Uploaded another file to my Unztrument (`trellis-monome`); to be fair to myself: It was late and I was tied.

This time everything went smoothly. But as you are so kind to answer anyway, I dare to ask for further steps. To give the context: I bought and soldered the Unztrument kit. There are two example scripts available for it: one is a simple midi pad controller script and the other a simple step sequencer. I spent some time trying to get into the programming (see if I could extend and adjust these examples) but this is kind of hard without any proper documentation and/or help. I planed to learn that much that I could (slowly but surely) program/build my own applications to control [Sonic Pi](https://github.com/samaaron/sonic-pi) with it. To get to the point: 

* As I understand from your documentation I could - now that the silly mistakes are overcome - go on and try using the Unztrument with Monome applications; I am not quite sure how to go on and would be grateful if you could give some further hints (being well aware of the fact that your time is precious)
* As a first step I will have to install `serialosc`, right?
* Can I test my Unztrument running your script without MAX/MSP? (I not planning to use MAX/MSP but from some googling I understand that there is a free version which can be used for some Monome applications and I would dive into it to hopefully acquire some knowledge how I could go on).
* What should I read or do to understand what exactly I will have to look into and learn to use my new Monome-for-the-poor?
* By the way: I am on Linux

Thanks for your time
Martin

**Comment by szymonkaliski** [comment]
Hey Martin,

so, Max/MSP is no-go for Linux anyways 😄
- for monome you need `serialosc`, yes; I had some problems with the official one though, so I wrote my own: https://github.com/szymonkaliski/node-serialoscd - BUT it was only tested with few apps, and I'm now using it with an app I wrote myself, so it might not be working everywhere, YMMV
- monome stuff is well documented here: https://monome.org/docs/ (you should be looking at "grid" documentation)
- most of monome apps are written in Max/MSP, but it also works with puredata (that runs on Linux), and should be pretty straightforward to run on SonicPi it it has a way to talk through OSC (afaik it does)

The way it works is:

`our fake monome <-(serial through usb cable)-> serialsc/node-serial-osc <-(osc on localhost)-> some app`

So if you want you can write your own app in whatever language you use, as long as it speaks proper OSC messages, these are documented here: https://monome.org/docs/osc/

Simplest test you could do, afaik, is probably to install my `node-serialoscd`, and run it with debug (`-d`) flag, hit some buttons and see if they log out to the console.

Keep in mind that both this hacky monome clone, and `node-serialoscd` etc. are unsupported by the original monome crew, I wrote them mainly for fun, and if I wanted something out-of-the-box I'd probably go for the original monome if I could afford it. Keeping all of that in mind, you might want to ask some questions on the monome forum as well: https://llllllll.co/

**Comment by mbutz** [comment]
Wow, that was fast and provides a good starting point. Already did install `serialosc`, still figuring out how it works... thanks for giving me something to chew on!

**Comment by szymonkaliski** [comment]
I'll close this issue since it's not really an issue anymore. Good luck with everything and in case of issues reach out either here, or hi@szymonkaliski.com or monome forum.
